# Generated by Django 2.2.1 on 2019-05-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('text', models.TextField(default='')),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LinhVuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
