# Generated by Django 2.2.1 on 2019-05-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_thanhpho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViecTheoDuAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('infojob', models.TextField(default='', max_length=500)),
                ('skill', models.CharField(default='', max_length=255)),
                ('time_ex', models.DateTimeField(default='')),
                ('ngansach', models.FloatField(default='', max_length=255)),
            ],
        ),
    ]
