# Generated by Django 2.2.1 on 2019-05-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_viectheoduan'),
    ]

    operations = [
        migrations.AddField(
            model_name='viectheoduan',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
